/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaceIdIndexRouteImport } from './routes/$placeId/index'
import { Route as PlaceIdParkingIdRouteImport } from './routes/$placeId/$parkingId'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as ProtectedAppIndexRouteImport } from './routes/_protected/app/index'
import { Route as ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRouteImport } from './routes/_protected/$placeId/$parkingId/$parkingSpotId/cart/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceIdIndexRoute = PlaceIdIndexRouteImport.update({
  id: '/$placeId/',
  path: '/$placeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceIdParkingIdRoute = PlaceIdParkingIdRouteImport.update({
  id: '/$placeId/$parkingId',
  path: '/$placeId/$parkingId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedAppIndexRoute = ProtectedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRoute =
  ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRouteImport.update({
    id: '/$placeId/$parkingId/$parkingSpotId/cart/',
    path: '/$placeId/$parkingId/$parkingSpotId/cart/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/$placeId/$parkingId': typeof PlaceIdParkingIdRoute
  '/$placeId/': typeof PlaceIdIndexRoute
  '/app/': typeof ProtectedAppIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/$placeId/$parkingId/$parkingSpotId/cart/': typeof ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/$placeId/$parkingId': typeof PlaceIdParkingIdRoute
  '/$placeId': typeof PlaceIdIndexRoute
  '/app': typeof ProtectedAppIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/$placeId/$parkingId/$parkingSpotId/cart': typeof ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/$placeId/$parkingId': typeof PlaceIdParkingIdRoute
  '/$placeId/': typeof PlaceIdIndexRoute
  '/_protected/app/': typeof ProtectedAppIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_protected/$placeId/$parkingId/$parkingSpotId/cart/': typeof ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$placeId/$parkingId'
    | '/$placeId/'
    | '/app/'
    | '/auth/reset-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/$placeId/$parkingId/$parkingSpotId/cart/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$placeId/$parkingId'
    | '/$placeId'
    | '/app'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/$placeId/$parkingId/$parkingSpotId/cart'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/$placeId/$parkingId'
    | '/$placeId/'
    | '/_protected/app/'
    | '/auth/reset-password/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/_protected/$placeId/$parkingId/$parkingSpotId/cart/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PlaceIdParkingIdRoute: typeof PlaceIdParkingIdRoute
  PlaceIdIndexRoute: typeof PlaceIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$placeId/': {
      id: '/$placeId/'
      path: '/$placeId'
      fullPath: '/$placeId/'
      preLoaderRoute: typeof PlaceIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$placeId/$parkingId': {
      id: '/$placeId/$parkingId'
      path: '/$placeId/$parkingId'
      fullPath: '/$placeId/$parkingId'
      preLoaderRoute: typeof PlaceIdParkingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up/'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/app/': {
      id: '/_protected/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof ProtectedAppIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$placeId/$parkingId/$parkingSpotId/cart/': {
      id: '/_protected/$placeId/$parkingId/$parkingSpotId/cart/'
      path: '/$placeId/$parkingId/$parkingSpotId/cart'
      fullPath: '/$placeId/$parkingId/$parkingSpotId/cart/'
      preLoaderRoute: typeof ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedAppIndexRoute: typeof ProtectedAppIndexRoute
  ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRoute: typeof ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAppIndexRoute: ProtectedAppIndexRoute,
  ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRoute:
    ProtectedPlaceIdParkingIdParkingSpotIdCartIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PlaceIdParkingIdRoute: PlaceIdParkingIdRoute,
  PlaceIdIndexRoute: PlaceIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
