/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as ProtectedAppIndexRouteImport } from './routes/_protected/app/index'
import { Route as ProtectedAppParkingsIndexRouteImport } from './routes/_protected/app/parkings/index'
import { Route as ProtectedAppAdminUsersIndexRouteImport } from './routes/_protected/app/admin-users/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedAppIndexRoute = ProtectedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAppParkingsIndexRoute =
  ProtectedAppParkingsIndexRouteImport.update({
    id: '/app/parkings/',
    path: '/app/parkings/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAppAdminUsersIndexRoute =
  ProtectedAppAdminUsersIndexRouteImport.update({
    id: '/app/admin-users/',
    path: '/app/admin-users/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/app/': typeof ProtectedAppIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/app/admin-users/': typeof ProtectedAppAdminUsersIndexRoute
  '/app/parkings/': typeof ProtectedAppParkingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/app': typeof ProtectedAppIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/app/admin-users': typeof ProtectedAppAdminUsersIndexRoute
  '/app/parkings': typeof ProtectedAppParkingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected/app/': typeof ProtectedAppIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/_protected/app/admin-users/': typeof ProtectedAppAdminUsersIndexRoute
  '/_protected/app/parkings/': typeof ProtectedAppParkingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/'
    | '/auth/sign-in/'
    | '/app/admin-users/'
    | '/app/parkings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/auth/sign-in'
    | '/app/admin-users'
    | '/app/parkings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/_protected/app/'
    | '/auth/sign-in/'
    | '/_protected/app/admin-users/'
    | '/_protected/app/parkings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/app/': {
      id: '/_protected/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof ProtectedAppIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/app/parkings/': {
      id: '/_protected/app/parkings/'
      path: '/app/parkings'
      fullPath: '/app/parkings/'
      preLoaderRoute: typeof ProtectedAppParkingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/app/admin-users/': {
      id: '/_protected/app/admin-users/'
      path: '/app/admin-users'
      fullPath: '/app/admin-users/'
      preLoaderRoute: typeof ProtectedAppAdminUsersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedAppIndexRoute: typeof ProtectedAppIndexRoute
  ProtectedAppAdminUsersIndexRoute: typeof ProtectedAppAdminUsersIndexRoute
  ProtectedAppParkingsIndexRoute: typeof ProtectedAppParkingsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAppIndexRoute: ProtectedAppIndexRoute,
  ProtectedAppAdminUsersIndexRoute: ProtectedAppAdminUsersIndexRoute,
  ProtectedAppParkingsIndexRoute: ProtectedAppParkingsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
