export const ORGANIZATION_USER_CREATED = 'CREATED';
export const ORGANIZATION_USER_INVITED = 'INVITED';
export const ORGANIZATION_USER_ACTIVE = 'ACTIVE';
export const ORGANIZATION_USER_SUSPENDED = 'SUSPENDED';
