name: CI

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate prisma client
        run: cd apps/api && npm run prisma:generate

      - name: Check types
        run: npm run check-types

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
